-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Mag 27, 2019 alle 22:23
-- Versione del server: 10.1.38-MariaDB
-- Versione PHP: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ag_templi`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `monumenti`
--

CREATE TABLE `monumenti` (
  `id_monumento` int(11) NOT NULL,
  `titolo` varchar(100) DEFAULT NULL,
  `descrizione` varchar(10000) DEFAULT NULL,
  `html_pages` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `monumenti`
--

INSERT INTO `monumenti` (`id_monumento`, `titolo`, `descrizione`, `html_pages`) VALUES
(1, 'Tempio di Demetra', '\r\nIl Tempio detto di Demetra (i cui resti si trovano in localita\' San Biagio al di sotto dell\'omonima chiesa) può essere datato nel periodo compreso tra il 480 e il 470 \r\n\r\na. C.<br><br> Questo tempio offre un interessante esempio di edificio distilo in antis ovvero privo del colonnato esterno e costituito da una semplice cella preceduta da un \r\n\r\npronao con due colonne.<br><br>\r\n\r\nDella struttura originaria si conservano il basamento di m 30×13 c.a, ancora in parte visibile, i muri esterni della cella e quelli divisori tra cella e pronao.<br><br> Queste \r\n\r\nparti che ancora permangono sono state inglobate dalla chiesa medievale dedicata a S. Biagio.<br><br> Delle belle grondaie a protome leonina appartenute a questo edificio si \r\n\r\npossono ancora ammirare all\'interno del museo archeologico regionale di Agrigento nella sala dedicata alle sculture architettoniche.<br><br>\r\n\r\nIl Tempio di Demetra nel periodo classico faceva parte di un temenos, un recinto sacro, al quale si devono riferire anche altre strutture adiacenti come due piccoli \r\n\r\naltari rotondi con incavo centrale, botroi o pozzi sacri, all\'interno dei quali sono stati ritrovati dei kernoi (vasi rituali legati al culto di Persefone) e dei resti \r\n\r\nappartenenti a dei busti fittili che dovevano raffigurare la stessa Demetra.\r\n', NULL),
(2, 'Tempio di Castore e Polluce', 'E\' quello che piu\' rappresenta la sigla di Agrigento artistica.<br><br>\r\n\r\nL\'alta piattaforma, montata su tre gradoni estesi all\'intero perimetro, misurava m. 34,12 in lunghezza e 15,86 in larghezza, poco meno di un doppio quadrato che \r\n\r\noccupava una superficie di mq.541,143. Delle 34 colonne, solo quattro si stagliano in mezzo a tutte quelle rovine.<br><br> Lo spigolo del tempio evidenzia un bellissimo \r\n\r\nrosone.<br><br>\r\n\r\nL\'edificio fu, nel 1836, sgombrato dalle pietre e dalla terra da che per molti secoli lo avevano ricoperto.<br><br> Villareale e Cavallari furono gli archeologi che , per \r\n\r\nordine del Duca di Serradifalco, rilevarono la pianta del tempio ed eressero su tre gradoni, tre colonne alle quali, nel 1856, ne aggiunsero una quarta.\r\n', 'castore.html'),
(3, 'Telamone', 'Il Telamone dell\'Olympeion e\' un telamone in calcarenite, databile tra il 480 e il 470 a.C. ed e\' una delle colossali statue che facevano parte dell\'enorme tempio di \r\n\r\nZeus ad Akragas e della cui funzione non si e\' a tutt\'oggi certi. e\' conservato presso il museo archeologico regionale di Agrigento.<br><br>\r\n\r\nIl colossale Telamone - ricomposto nel 1825 - e\' addossato alla parete di fondo della sala \'Cavallari\': conservato insieme a 3 teste di altri Telamoni.<br><br>\r\n\r\n\r\nLa statua e\' alta 7,65 metri ed e\' la piu\' grande dell\'antichita\' in Sicilia e tra le piu\' grandi dell\'intera arte greca. Una riproduzione del suddetto Telamone e\' adagiato \r\n\r\nper terra tra le rovine del tempio.', NULL),
(4, 'Museo Archeologico Regionale', 'Il Museo Archeologico Regionale “Pietro Griffo” di Agrigento in Contrada San Nicola e\' sicuramente uno dei musei archeologici piu\' importanti e piu\' visitati della \r\n\r\nSicilia. <br><br>L\'edificio e\' stato progettato da Franco Minissi e realizzato negli anni \'60 sul poggetto di San Nicola dove sorgeva l\'agora\' superiore della citta\' antica e, in \r\n\r\nepoca piu\' recente, la villa del Ciantro Panitteri.<br><br>\r\n\r\nMirabile la fusione tra fabbriche antiche (Chiostro di San Nicola) e strutture moderne. Il museo archeologico espone ben 5688 reperti che, ordinati secondo un criterio \r\n\r\ncronologico e topografico, illustrano la storia del territorio agrigentino dalla preistoria fino alla fine dell\'eta\' greco-romana.<br><br> I materiali provengono dai fondi del \r\n\r\nMuseo Civico, relativi agli scavi archeologici condotti nei primi decenni del secolo scorso, da collezioni private o sono stati ceduti dai musei archeologici di \r\n\r\nPalermo e di Siracusa.<br><br>\r\n\r\nLa parte piu\' consistente delle collezioni e\' pero\' rappresentata dai reperti rinvenuti dalla Soprintendenza di Agrigento nelle campagne di scavo condotte dagli anni \r\n\r\nquaranta fino ai nostri giorni.<br><br> L\'esposizione si articola in 18 sale e in due sezioni distinte, ma complementari. In ogni sala pannelli esplicativi bilingue (italiano \r\n\r\ne inglese) orientano i visitatori e danno informazioni sui materiali esposti nelle vetrine.\r\n', NULL),
(5, 'Tempio di Ercole', 'Uno dei piu\' belli dell\'antichita\' (510 a.C), e\' ora ridotto in povere vestigia.<br><br> Ma anche cosi\' l\'edificio, visibile da lontano, e\' imponente e sorge nella Valle dei Templi \r\n\r\nproprio come il simbolo della potenza e della forza di Eracle, l\'eroe nazionale della Sicilia e, in particolare, di Agrigento.<br><br>\r\n\r\nL\'ampia piattaforma rettangolare, montata su quattro gradoni, misura m.73,992 in lunghezza e 27,788 in larghezza, un triplice quadrato che occupa una superficie di \r\n\r\nmq.2.056,89 e raggiungeva un\'altezza di m. 16,264.<br><br>\r\n\r\nDelle 38 colonne (6 sui frontoni e 15 sui lati lunghi contando anche quelle degli angoli), solo 9, rialzate nel 1922, grazie alla munificenza del capitano inglese \r\n\r\nAlexander Hardcastle, si stagliano, col loro aspetto imponente, in mezzo a tutte le rovine.', 'ercole.html'),
(6, 'Tomba di Terone', 'E\' un piccolo monumento funerario romano (sec. I a.C.), facente parte della cosiddetta necropoli Giambertoni (sec. I-III d.C.), vasto cimitero steso sulle pendici della \r\n\r\ncollina, subito fuori dalle antiche mura. Per raggiungerlo si lascia a destra il vasto piazzale del parcheggio per la Valle dei Templi (realizzato nell\'area \r\n\r\ndell\'agora\') e si prosegue lungo la statale, attraversando, dopo una brusca svolta, gli scarsi resti della porta IV o porta Aurea, principale accesso della greca \r\n\r\n«Akragas».\r\nLa tomba di Terone risulta composta di due parti sovrapposte: un podio cubico e un tempietto a base quadrata, con porte cieche su ogni lato e colonne angolari doriche \r\n\r\ncon capitelli e basamenti ionici. Piu\' a sud, sulla riva destra dell\'Akragas, sono gli avanzi del tempio di Esculapio, piccolo edificio (sec. V a.C.) in antis e con \r\n\r\npseudocolonne sul lato ovest.', NULL),
(7, 'Tempio della Concordia', 'Innalzato intorno al 430 a.C. <br><br>E\' un quadrilatero di 19,758 metri per 42,230, poco piu\' di un doppio quadrato che occupa una superficie di mq.843,38 e sviluppa \r\n\r\nun\'altezza di metri 13,481.<br><br>\r\n\r\nLa cella era preceduta da una semplice anticamera a due colonne  ed era seguita, alle spalle, da un altro vestibolo , ovvero il vano per la custodia del tesoro, dei doni votivi e dell\'archivio del tempio.<br><br>L\'elegante e arioso colonnato, secondo i modelli classici, ha 6 colonne \r\n\r\nper 13; ogni colonna, dell\'altezza di m. 6,75, e\' costituita da 4 tamburi, con un fascio di 20 scanalature a spigolo vivo.<br><br>\r\n\r\nIl tempio deve il suo nome allo storico Fazello (1490- 1570), il quale rinvenne un\'iscrizione latina nelle vicinanze, non avente, invero, alcun rapporto con il tempio. <br><br>\r\nNel 597 il tempio fu trasformato in basilica cristiana dal vescovo Gregorio, dopo esservi stati abbattuti due idoli pagani; e poiche\' uno di essi nomavasi Raps, la \r\n\r\nChiesa fu poi consacrata a S.Gregorio delle Rape.\r\n', 'concordia.html'),
(8, 'Quartiere Ellenistico Romano', 'Nelle vicinanze del poggio San Nicola, su una vasta area di circa 15 mila mq. si estende il cosiddetto quartiere ellenistico-romano, un settore urbano con tracciato \r\n\r\nregolare che ricalca per orientamento ed impostazione quello che doveva essere l\'impianto urbanistico della citta\' del periodo classico.<br><br>\r\n\r\nIl quartiere e\' caratterizzato da quattro cardi (strade secondarie) larghi circa cinque metri e distanti tra loro 35 m. secondo un orientamento sud/nord, che si \r\n\r\nincrociano ortogonalmente con tre decumani (strade principali) ampie 7 m. orientate est/ovest.<br><br> Il sistema viario del quartiere ellenistico- romano ospitava delle \r\n\r\nabitazioni distinte a loro volta, come da tradizione greca, da stretti ambitus o intercapedini che dovevano servire al passaggio veloce da un isolato all\'altro per i \r\n\r\npedoni.<br><br>\r\n\r\nLe abitazioni sono di vario tipo: alcune a peristilio, secondo una tradizione prettamente ellenistica, altre invece con atrio caratterizzato da impluvio di tipo \r\n\r\nitalico, sia con peristilio che semplicemente circondate da vani. Da un punto di vista del materiale utilizzato, secondo l\'uso greco classico, le case sono state \r\n\r\nrealizzate in blocchi di arenaria, tralasciando conglomerati e laterizi come ci si aspetterebbe da un quartiere di epoca romana.<br><br>\r\n\r\nMolte abitazioni si presentano particolarmente curate sia per le tracce di stucchi e dipinti alle pareti sia, e soprattutto, per la presenza di pavimenti musivi la cui \r\n\r\nrealizzazione varia da semplici tessere in opus signinum o tessellatum di tarda eta\' repubblicana a rappresentazioni figurative di vario tipo dei primi secoli \r\n\r\ndell\'impero aventi un\'iconografia caratteristica delle maestranze di tradizione africana.', 'romano.html'),
(9, 'Tempio di Giunone', 'Il nome del tempio e\', come quello di altri monumenti agrigentini, convenzionale. Nell\'architettura di questo tempio, eretto nell\'angolo di sud-est della valle dei \r\n\r\ntempli a 120 metri s.l.m., e\' evidente la preoccupazione di una perfezione artistica rigorosa. <br><br>L\'edificio, che e\' rivolto, come gli altri, ad oriente, ha dimensioni \r\n\r\nnotevoli: l\'alta piattaforma rettangolare montata su quattro gradoni, sulla quale riposano 34 colonne che si presentano 6 sui frontoni e 13 sui lati lunghi, contando \r\n\r\nanche quelle degli angoli, misura m.41,106 in lunghezza e 20,260 in larghezza.<br><br>\r\n\r\nUn doppio quadrato che occupa una superficie di mq.832,807. La colonna formata da quattro tamburi o rocchi, con un fascio di 20 scanalature a spigolo vivo, raggiunge \r\n\r\nun\'altezza di metri 6,32 e ha un diametro di metri 1,70; distano metri 1,71 al centro e 1,76 ai lati. <br><br>La costruzione e\' avvenuta intorno al 450-440 a.C.<br><br>\r\n\r\nSi conservano 30 colonne, di cui sedici con capitello. Fu restaurato dal Torremuzza nel 1787', 'giunone.html'),
(10, 'Casa natale di Luigi Pirandello ', 'La casa natale di Luigi Pirandello si trova in una contrada di campagna, a strapiombo sul mare, denominata “Caos”, al confine tra il territorio del comune di Agrigento \r\n\r\n(4 chilometri) e quello del comune di Porto Empedocle. Si raggiunge percorrendo la strada statale 115 in direzione di Villaseta.\r\n\r\nLa casa era, in origine, una costruzione rurale di fine Settecento, nella disponibilta\' della famiglia Ricci Gramitto, avi di parte materna dello scrittore. Qui, \r\n\r\nCaterina Ricci Gramitto, madre di Luigi, si era rifugiata per sfuggire alla grave epidemia di colera che nel 1867 imperversava in Sicilia. Passato ad altri proprietari \r\n\r\nin seguito al tracollo economico della famiglia Pirandello, l\'edificio fu danneggiato nel 1943 dallo scoppio di un vicino deposito di munizioni e fu dichiarato \r\n\r\nmonumento nazionale nel 1949. In seguito all\' acquisizione, nel 1952, da parte dalla Regione Siciliana, furono intrapresi dei lavori di restauro e sistemazione che \r\n\r\nhanno dato ai luoghi l\'aspetto attuale.\r\n\r\nLe stanze del piano superiore con vista sulla campagna circostante ospitano oggetti personali, fotografie, onoreficenze, recensioni, lettere, manoscritti e prime \r\n\r\nedizioni di libri con dediche autografe, locandine delle opere piu famose del grande scrittore agrigentino e il vaso greco servito per traslare le sue ceneri dal \r\n\r\ncimitero del Verano a Agrigento. Il pianterreno ospita, periodicamente, mostre temporanee dedicate al Maestro.\r\n', NULL),
(11, 'Tempio di Esculapio', 'Era qui che malati e infermi accorrevano per ricevere cure e consigli.\r\n\r\nL\'edificio, ci dice Polibio, distava dalla citta\' otto stadi e mezzo, ossia 1480 metri. Cicerone afferma che nel tempio c\'era una statua di Apollo, opera di Mirone, il \r\n\r\ncui nome era inciso, con lettere d\'argento in una coscia del capolavoro.\r\n\r\nIl Tempio di Asclepio era, in se stesso, un edificio molto modesto: lungo m.22,144 e largo 11,118, occupa una superficie di mq.246,196, e la sua decorazione era di \r\n\r\ngran lunga inferiore ai templi dorici classici. Lo spessore delle mura e\' di m.0,55; il diametro delle colonne e\' di m.1,10.', NULL),
(12, 'Giardino della Kolymbetra', 'Gioiello protetto dalla Valle dei Templi e custodito dalla Storia. Autentico tesoro archeologico e agricolo siciliano: un giardino che celebra la magnificenza della \r\n\r\nnatura in tutta la sua generosita\'!\r\n', 'giardino.html'),
(14, 'Tempio di Vulcano', 'Il tempio di Vulcano (in greco Efesto) sorge sulla collina a Ovest dell\'odierno giardino della Kolymbetra, che lo separa dall\'estremita\' Sud-ovest della collina dei Templi e dal santuario delle Divinita\' Ctonie.\r\n\r\nLa tradizionale denominazione di tempio di Vulcano – come spesso accade ad Agrigento – e\' soltanto convenzionale e non e\' supportata ne\' da riscontri archeologici né epigrafici. Il suo nome si deve all\'interpretazione di un brano di Solino, scrittore latino di geografia, che accenna alle cerimonie religiose che si svolgevano presso un lago agrigentino non lontano dal colle di Vulcano (collis Vulcanius), cosiddetto forse per la presenza di sorgenti di Zolfo.\r\n\r\nDel tempio non resta quasi nulla, ad eccezione di piccoli tratti del basamento con quattro gradini e due colonne superstiti.', NULL);

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `monumenti`
--
ALTER TABLE `monumenti`
  ADD PRIMARY KEY (`id_monumento`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
